PROGRAM TEST

USE MPL_END_MOD, ONLY : MPL_END
USE MPL_INIT_MOD, ONLY : MPL_INIT
USE PARKIND1, ONLY : JPIM, JPRB
USE MPL_MODULE, ONLY : MPL_MYRANK, MPL_GROUPS_CREATE, MPL_NUMPROC
USE MPL_BARRIER_MOD, ONLY : MPL_BARRIER
USE YOMHOOK, ONLY : DR_HOOK, LHOOK

USE HADES

IMPLICIT NONE

INTEGER(KIND=JPIM) :: NPRGPNS, NPRGPEW, NPRTRW, NPRTRV, NPRINTLEV
INTEGER(KIND=JPIM) :: MYPROC, NPROC

INTEGER (KIND=JPIM) :: IA, IB

LOGICAL :: LPRINT

TYPE (GRID_OPTIONS_t), TARGET :: YLGROPT1, YLGROPT2
TYPE (GRID_OPTIONS_t), POINTER :: YLGROPT
TYPE (GRID_t) :: YLGRID1, YLGRID2
TYPE (DIST_t) :: YLDIST1, YLDIST2

#include "setup_trans0.h"
#include "trans_inq.h"
#include "dist_grid.h"
#include "gath_grid.h"
#include "dir_trans.h"
#include "inv_trans.h"
#include "posnam.intfb.h"

NAMELIST / NAMAATESTPROG / NPRINTLEV, LPRINT
NAMELIST / NAMGRID1 / YLGROPT
NAMELIST / NAMGRID2 / YLGROPT

REAL (KIND=JPRB) :: ZHOOK_HANDLE

OPEN (4, FORM='FORMATTED')

NPRINTLEV = 0
LPRINT    = .FALSE.

CALL POSNAM (4, 'NAMAATESTPROG')
READ (4, NAMAATESTPROG)

CALL POSNAM (4, 'NAMGRID1')
YLGROPT => YLGROPT1
READ (4, NAMGRID1)

CALL POSNAM (4, 'NAMGRID2')
YLGROPT => YLGROPT2
READ (4, NAMGRID2)

NULLIFY (YLGROPT)

CALL MPL_INIT (LDENV = .FALSE.)

MYPROC = MPL_MYRANK ()
NPROC  = MPL_NUMPROC

CALL SQUARE (NPROC, IA, IB)

NPRGPNS = IA
NPRGPEW = IB
NPRTRW  = IA
NPRTRV  = IB

CALL MPL_GROUPS_CREATE (NPRTRW, NPRTRV)

CALL SETUP_TRANS0 (KOUT=0, KERR=0, KPRINTLEV=NPRINTLEV, KMAX_RESOL=3,  &
                 & KPRGPNS=NPRGPNS, KPRGPEW=NPRGPEW, KPRTRW=NPRTRW,    &
                 & LDEQ_REGIONS=.TRUE.)

CALL MPL_BARRIER()

IF (LHOOK) CALL DR_HOOK ('AATESTPROG',0,ZHOOK_HANDLE)

CALL CREATE_GRID_DIST (YLGRID1, YLDIST1, YLGROPT1)
CALL CREATE_GRID_DIST (YLGRID2, YLDIST2, YLGROPT2)

LPRINT = .TRUE.
#ifdef UNDEF
CALL DEMO_LATLON (YLDIST1, YLGRID1, LPRINT)
CALL DEMO_GATHDIST (YLDIST1, YLGRID1, 1, .TRUE., LPRINT)
CALL DEMO_HALO (YLGRID1, YLDIST1, LPRINT)
#endif
CALL DEMO_GRADIENT (YLDIST1, YLGRID1)
#ifdef UNDEF
CALL DEMO_LATLON (YLDIST2, YLGRID2, LPRINT)
CALL DEMO_GATHDIST (YLDIST2, YLGRID2, 1, .TRUE., LPRINT)
CALL DEMO_HALO (YLGRID2, YLDIST2, LPRINT)
CALL DEMO_SHUFFLE (YLDIST1, YLGRID1, YLDIST2, YLGRID2, LPRINT)
CALL DEMO_GRADIENT (YLDIST2, YLGRID2)
CALL DEMO_INTERPOLATION (YLDIST1, YLGRID1, YLDIST2, YLGRID2, LPRINT)
#endif


IF (LHOOK) CALL DR_HOOK ('AATESTPROG',1,ZHOOK_HANDLE)

CALL MPL_END

CONTAINS

SUBROUTINE SQUARE (KN, KA, KB)

INTEGER (KIND=JPIM) :: KN, KA, KB

KB = INT (SQRT (REAL (KN))) + 1

DO
  KA = KN / KB
  IF (KA * KB == KN) EXIT
  KB = KB - 1
ENDDO

END SUBROUTINE SQUARE

END PROGRAM TEST


