PROGRAM TEST

USE MPL_END_MOD, ONLY : MPL_END
USE MPL_INIT_MOD, ONLY : MPL_INIT
USE PARKIND1, ONLY : JPIM, JPRB
USE MPL_MODULE, ONLY : MPL_MYRANK, MPL_GROUPS_CREATE, MPL_NUMPROC
USE MPL_BARRIER_MOD, ONLY : MPL_BARRIER
USE YOMHOOK, ONLY : DR_HOOK, LHOOK

USE HADES

IMPLICIT NONE

INTEGER(KIND=JPIM) :: NPRGPNS, NPRGPEW, NPRTRW, NPRTRV, NPRINTLEV
INTEGER(KIND=JPIM) :: MYPROC, NPROC

#include "setup_trans0.h"
#include "trans_inq.h"
#include "dist_grid.h"
#include "gath_grid.h"
#include "dist_spec.h"
#include "gath_spec.h"
#include "dir_trans.h"
#include "inv_trans.h"
#include "posnam.intfb.h"
#include "faieno.h"


REAL (KIND=JPRB),   ALLOCATABLE :: ZSPBUFL (:,:) 
REAL (KIND=JPRB),   ALLOCATABLE :: ZSPBUFG (:,:) 
REAL (KIND=JPRB),   ALLOCATABLE :: ZGPBUFL (:,:,:) 
REAL (KIND=JPRB),   ALLOCATABLE :: ZGPBUFG (:,:) 


TYPE (GRID_t) :: YLGRID
TYPE (DIST_t) :: YLDIST
TYPE (GRID_OPTIONS_t) :: YLGROPT
CHARACTER (LEN=64) :: CLFILENAME
CHARACTER (LEN=64),  PARAMETER :: CLNOMC = 'c'
INTEGER (KIND=JPIM), PARAMETER :: ILUN = 77
INTEGER (KIND=JPIM) :: INBARP, INBARI, IREP, INIMES, IVSET (1)

REAL (KIND=JPRB) :: ZHOOK_HANDLE

CALL GETARG (1, CLFILENAME)

CALL MPL_INIT (LDENV = .FALSE.)

MYPROC = MPL_MYRANK ()
NPROC  = MPL_NUMPROC

NPRGPNS = NPROC
NPRGPEW = 1
NPRTRW  = NPROC
NPRTRV  = 1

CALL MPL_GROUPS_CREATE (NPRTRW, NPRTRV)

NPRINTLEV = 0
CALL SETUP_TRANS0 (KOUT=0, KERR=0, KPRINTLEV=NPRINTLEV, KMAX_RESOL=3,  &
                 & KPRGPNS=NPRGPNS, KPRGPEW=NPRGPEW, KPRTRW=NPRTRW,    &
                 & LDEQ_REGIONS=.TRUE.)

CALL MPL_BARRIER()

IF (LHOOK) CALL DR_HOOK ('SPECSURFGEOPOTEN',0,ZHOOK_HANDLE)

YLGROPT%LGRIDONLY = .FALSE.
CALL CREATE_GRID_DIST_FA (YLGRID, YLDIST, CLFILENAME, YLGROPT)


ALLOCATE (ZGPBUFL (YLDIST%NGPTOTL (MYPROC), 1, 1))
ALLOCATE (ZSPBUFL (1, YLDIST%NSPEC2L (MYPROC)))


CALL RFA (ZGPBUFL, YLDIST%NGPTOTL (MYPROC), 1_JPIM, CLFILENAME, ['SURF'], &
        & [0_JPIM], ['GEOPOTENTIEL'], YLGRID, YLDIST)

CALL WFA (ZGPBUFL, YLDIST%NGPTOTL (MYPROC), 1_JPIM, TRIM (CLFILENAME)//'.0', ['SURF'], &
        & [0_JPIM], ['GEOPOTENTIEL'], YLGRID, YLDIST)


IVSET (1) = 1

CALL DIR_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)
CALL INV_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)

IF (MYPROC == 1) THEN
  INBARI = 0
  INBARP = 0
  INIMES = 2
  CALL FAITOU (IREP, ILUN, .TRUE., CLFILENAME, 'OLD', .TRUE., .TRUE., INIMES, INBARP, INBARI, CLNOMC)

  BLOCK
    INTEGER (KIND=JPIM) :: INGRIB, INARG1, INARG2, INARG3, INARG4, INARG5
    CALL FAVEUR (IREP, ILUN, INGRIB, INARG1, INARG2, INARG3, INARG4, INARG5)
    INGRIB = 123_JPIM
    CALL FAGOTE (IREP, ILUN, INGRIB, INARG1, INARG2, INARG3, INARG4, INARG5)
  ENDBLOCK

  ALLOCATE (ZGPBUFG (YLGRID%NGPTOTG, 1))
  CALL GATH_GRID (PGPG=ZGPBUFG, KFGATHG=1, KTO = [1_JPIM], PGP=ZGPBUFL)
  CALL FAIENO (IREP, ILUN, "SURF", 0, "GEOPOTENTIEL", ZGPBUFG (1, 1), .FALSE.)
  DEALLOCATE (ZGPBUFG)

  ALLOCATE (ZSPBUFG (1, YLGRID%NSPEC2G))
  CALL GATH_SPEC (PSPECG=ZSPBUFG, KFGATHG=1, KTO = [1_JPIM], KVSET=IVSET, PSPEC=ZSPBUFL)
  CALL FAIENO (IREP, ILUN, "SPEC", 0, "SURFGEOPOTEN", ZSPBUFG (1, 1), .TRUE.)
  DEALLOCATE (ZSPBUFG)

ELSE
  CALL GATH_GRID (KFGATHG=1, KTO = [1_JPIM], PGP=ZGPBUFL)
  CALL GATH_SPEC (KFGATHG=1, KTO = [1_JPIM], KVSET=IVSET, PSPEC=ZSPBUFL)
ENDIF

IF (MYPROC == 1) THEN
  CALL FAIRME (IREP, ILUN, 'KEEP')
ENDIF

CALL WFA (ZGPBUFL, YLDIST%NGPTOTL (MYPROC), 1_JPIM, TRIM (CLFILENAME)//'.1', ['SURF'], &
        & [0_JPIM], ['GEOPOTENTIEL'], YLGRID, YLDIST)

CALL DIR_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)
CALL INV_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)

CALL WFA (ZGPBUFL, YLDIST%NGPTOTL (MYPROC), 1_JPIM, TRIM (CLFILENAME)//'.2', ['SURF'], &
        & [0_JPIM], ['GEOPOTENTIEL'], YLGRID, YLDIST)

CALL DIR_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)
CALL INV_TRANS (PSPSCALAR=ZSPBUFL, PGP=ZGPBUFL, KVSETSC=IVSET)

CALL WFA (ZGPBUFL, YLDIST%NGPTOTL (MYPROC), 1_JPIM, TRIM (CLFILENAME)//'.3', ['SURF'], &
        & [0_JPIM], ['GEOPOTENTIEL'], YLGRID, YLDIST)


IF (LHOOK) CALL DR_HOOK ('SPECSURFGEOPOTEN',1,ZHOOK_HANDLE)

CALL MPL_END

END PROGRAM

