SUBROUTINE FALIST

USE PARKIND1, ONLY : JPIM, JPRB, JPIA, JPIB, JPRD
USE LFI_PRECISION
#ifdef UNDEF
USE MODD_IO_SURF_ARO, ONLY : SURFEX_FIELD_BUF_READ_MISC, &
                           & SURFEX_FIELD_BUF_CACHE
#endif
USE FA_MOD, ONLY : FA_COM
USE YOMHOOK, ONLY : DR_HOOK, LHOOK
                           

IMPLICIT NONE

#include "fadoco.h"

INTEGER, PARAMETER :: ILUN = 77
INTEGER :: ILUNR = 99
CHARACTER (LEN=*), PARAMETER :: CLNOMC = 'cadre'
CHARACTER (LEN=16), PARAMETER :: CLSKIP (11) = &
& (/ 'CADRE-DIMENSIONS', 'CADRE-FRANKSCHMI',   &
&    'CADRE-REDPOINPOL', 'CADRE-SINLATITUD',   &
&    'CADRE-FOCOHYBRID', 'FULLPOS         ',   &
&    'DATE-DES-DONNEES', 'ARP             ',   &
&    'DATX-DES-DONNEES', 'ALD             ',   &
&    'header          ' /)

CHARACTER (LEN=16), ALLOCATABLE :: CLNOMS (:)
REAL (KIND=JPRD) :: ZVALCO (8)
REAL (KIND=JPRB), ALLOCATABLE :: ZCHAMP (:)
CHARACTER (LEN=128) :: CLF
INTEGER (KIND=JPIM) :: INBARP, INBARI, IREP
INTEGER (KIND=JPIM) :: ILONGD, IPOSEX, INALDO, INTROU, INARES, INAMAX, ILNOMA
INTEGER (KIND=JPIM) :: IARTL, INIVAU, INBITS, ISTRON, IPUILA
INTEGER (KIND=JPIM) :: INGRIB
INTEGER (KIND=JPIM) :: I, INIMES
INTEGER (KIND=JPIM) :: ILCHAM_SP, ILCHAM_GP, ILCHAM
CHARACTER (LEN=16) :: CLPREF, CLSUFF, CLNOMA
LOGICAL :: LLSURFEX, LLCOSP, LLEXIS
#ifdef UNDEF
TYPE (SURFEX_FIELD_BUF_CACHE) :: YLSC
#endif

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('FALIST',0,ZHOOK_HANDLE)

CALL GETARG (2, CLF)

INBARP=0
INBARI=0
CALL FAITOU (IREP, ILUN, .TRUE., CLF, 'OLD', .TRUE., .FALSE., 0_JPIM, INBARP, INBARI, CLNOMC)

CALL FATCHA (IREP, CLNOMC, .TRUE., ILCHAM_SP)
CALL FATCHA (IREP, CLNOMC, .FALSE., ILCHAM_GP)

CALL LFINFO (IREP, ILUN, 'SFX._FBUF_NAME', ILONGD, IPOSEX)
LLSURFEX = ILONGD > 0

IF (LLSURFEX .AND. .FALSE.) THEN
#ifdef UNDEF
  CALL SURFEX_FIELD_BUF_READ_MISC (YLSC, ILUN, LDMPI=.FALSE.)

  INALDO = 0

  DO IARTL = 1, SIZE (YLSC%P)
    SELECT CASE (YLSC%P (IARTL)%TYPE)
      CASE ('X1')
        INALDO = INALDO + 1
      CASE ('X2')
        INALDO = INALDO + YLSC%P (IARTL)%NDIM (2)
    END SELECT
  ENDDO
  
  ALLOCATE (CLNOMS (INALDO))
  
  INALDO = 0

  DO IARTL = 1, SIZE (YLSC%P)
    SELECT CASE (YLSC%P (IARTL)%TYPE)
      CASE ('X1')
        INALDO = INALDO + 1
        CLNOMS (INALDO) = 'SFX.'//YLSC%P (IARTL)%NAME
      CASE ('X2')
        DO I = 1, YLSC%P (IARTL)%NDIM (2)
          INALDO = INALDO + 1
          WRITE (CLNOMS (INALDO), '("X",I3.3,A)') I, TRIM (YLSC%P (IARTL)%NAME)
        ENDDO
    END SELECT
  ENDDO
#endif
ELSE

  CALL LFINAF (IREP, ILUN, INALDO, INTROU, INARES, INAMAX)

  ALLOCATE (CLNOMS (INALDO))

  CALL LFIPOS (IREP, ILUN)

  DO IARTL = 1, INALDO

    CALL LFICAS (IREP, ILUN, CLNOMS (IARTL), ILONGD, IPOSEX, .TRUE.)

    IF (ILONGD == 0) EXIT

  ENDDO

ENDIF

DO IARTL = 1, INALDO

  CLNOMA = CLNOMS (IARTL)

  IF (ANY (CLNOMA == CLSKIP)) CYCLE

  CALL FAQUIN (IREP, ILUN, CLPREF, INIVAU, CLSUFF, &
             & CLNOMA, LEN_TRIM (CLNOMA))

! Read field features
  CALL FANION (IREP, ILUN, CLPREF, INIVAU, CLSUFF, LLEXIS, &
             & LLCOSP, INGRIB, INBITS, ISTRON, IPUILA)

  CALL LFINFO (IREP, ILUN, CLNOMA, ILONGD, IPOSEX)
  WRITE (*, '("[ ",A50,", ",I15,", ",I15,", ",I5,", ",L1,", ",I5," ],")')  &
 &   "'"//TRIM(CLNOMA)//"'", ILONGD, IPOSEX, INGRIB, LLCOSP, INBITS

ENDDO

CALL FAIRME (IREP, ILUN, 'KEEP')

DEALLOCATE (CLNOMS)

IF (LHOOK) CALL DR_HOOK ('FALIST',1,ZHOOK_HANDLE)

END SUBROUTINE FALIST

