SUBROUTINE LFIGRIB2FA

USE PARKIND1, ONLY : JPRB, JPIM
USE XRD_GETOPTIONS
USE LFI_PRECISION
USE FA_MOD, ONLY : FA => FA_COM_DEFAULT

IMPLICIT NONE

#include "faieno.h"

INTEGER, PARAMETER :: ILUN = 77
CHARACTER (LEN=128) :: CLF, CLG
INTEGER :: INBARP, INBARI, IREP
INTEGER :: I, K
CHARACTER (LEN=16) :: CLNOMA
INTEGER*8 :: IERR8, IFP, IST (13), ISIZE, ISIZEBUF
INTEGER*4 :: IERR4, INO
INTEGER*8, ALLOCATABLE :: IBUF (:)

CALL INITOPTIONS (KOPTMIN=1)
CALL GETOPTION ('--fa-file', CLF, MND = .TRUE.)
CALL GETOPTION ('--grib-file', CLG, MND = .TRUE.)
CALL GETOPTION ('--name', CLNOMA, MND = .TRUE.)
CALL CHECKOPTIONS ()

INBARI=0
CALL LFIOUV (IREP, ILUN, .TRUE., CLF, 'OLD', .TRUE., .FALSE., 0_JPIM, INBARP, INBARI)
CALL FI_FOPEN (IFP, TRIM (CLG), "r")
CALL FI_FILENO (INO, IFP)
CALL FI_FSTAT (IERR4, INO, IST)

ISIZE = IST (8)

PRINT *, " ISIZE = ", ISIZE

ISIZEBUF = 3 + (ISIZE + 7) / 8

ALLOCATE (IBUF (ISIZEBUF))
IBUF (1) = 160
IBUF (2) =   0
IBUF (3) =  16

CALL FI_FREAD (IERR8, IBUF (4), ISIZE, 1_8, IFP)

CALL LFIECR (IREP, ILUN, TRIM (CLNOMA), IBUF, ISIZEBUF)

CALL FI_FCLOSE (IERR4, IFP)
CALL LFIFER (IREP, ILUN, 'KEEP')


END SUBROUTINE LFIGRIB2FA

