SUBROUTINE LFIXXX

USE PARKIND1, ONLY : JPRB, JPIM
USE XRD_GETOPTIONS
USE LFI_PRECISION

IMPLICIT NONE

CHARACTER (LEN=*), PARAMETER :: CLNOMC = 'c'
INTEGER (KIND=JPIM) :: ILUN = 77, INIMES = 2, INBARP = 0, INBARI = 0
INTEGER (KIND=JPIM) :: IRET, INBITS, INGRIB = 120, IREP, INIVAU
INTEGER (KIND=JPIM) :: ISTRON, IPUILA, JFLD, ILCHAM, IDMOPL
REAL (KIND=JPRB), ALLOCATABLE :: ZCHAMP (:)
LOGICAL :: LLEXIS, LLCOSP
CHARACTER (LEN=16), POINTER :: CLNOMA (:) => NULL ()
CHARACTER (LEN=16) :: CLPREF, CLSUFF
CHARACTER (LEN=64) :: CLFILE

CALL INITOPTIONS (KOPTMIN=1)

CALL GETOPTION ("--fa-file", CLFILE, MND = .TRUE.)
CALL GETOPTION ("--clnoma", CLNOMA, MND = .TRUE.)

CALL CHECKOPTIONS ()


CALL FAITOU (IREP, ILUN, .TRUE., TRIM (CLFILE), 'OLD', .TRUE., &
           & .FALSE., INIMES, INBARP, INBARI, CLNOMC)

CALL FATCHA (IREP, CLNOMC, .FALSE., ILCHAM)

ALLOCATE (ZCHAMP (ILCHAM))

DO JFLD = 1, SIZE (CLNOMA)

  CALL FAQUIN (IREP, ILUN, CLPREF, INIVAU, CLSUFF, CLNOMA (JFLD), LEN_TRIM (CLNOMA (JFLD)))
  CALL FANION (IREP, ILUN, CLPREF, INIVAU, CLSUFF, LLEXIS, LLCOSP, INGRIB, INBITS, ISTRON, IPUILA)
  
  CALL FAGOTE (IREP, ILUN, INGRIB, INBITS, INBITS, ISTRON, IPUILA, IDMOPL)

  CALL FACILE (IREP, ILUN, CLPREF, INIVAU, CLSUFF, ZCHAMP, .FALSE.)

  WHERE (ABS (ZCHAMP - 9999._JPRB) < 0.1_JPRB)
    ZCHAMP = 0._JPRB
  ENDWHERE

  CALL FAIENC (IREP, ILUN, CLPREF, INIVAU, CLSUFF, ZCHAMP, .FALSE.)

ENDDO

CALL FAIRME (IREP, ILUN, 'KEEP')

END

