PROGRAM ATLAS_PGD_POINTS

USE PARKIND1, ONLY : JPIM, JPRB
USE ATLAS_IO_FIELDSET, ONLY : ATLAS_IO_FIELDSET_t
USE ATLAS_DH, ONLY : ATLAS_DH_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE FCKIT_MPI_MODULE, ONLY : FCKIT_MPI_SETCOMMDEFAULT
USE ATLAS_MODULE  
USE ATLAS_TRACE_MODULE

!

IMPLICIT NONE

#include "atlas-pgd-impl.h"

TYPE (ATLAS_IO_FIELDSET_t)     :: YLIOFS
TYPE (ATLAS_DH_t)              :: YLDHIO
TYPE (ATLAS_STRUCTUREDGRID)    :: YLGRID2
TYPE (ATLAS_TRACE)             :: YLTRAC

INTEGER (KIND=JPIM) :: NPROC, IRANK, JLOC
INTEGER (KIND=JPIM) :: ISIZE
TYPE (FCKIT_MPI_COMM) :: YLWORLD, YLSPLIT

CALL ATLAS_LIBRARY%INITIALISE ()

YLTRAC = ATLAS_TRACE (__FILE__, __LINE__, "ATLAS_PGD")

YLWORLD = FCKIT_MPI_COMM ()

print *, " YLWORLD%NAME () = ", YLWORLD%NAME ()

NPROC  = YLWORLD%SIZE ()
IRANK  = YLWORLD%RANK ()

CALL LINUX_BIND (IRANK, NPROC)

YLSPLIT = YLWORLD%SPLIT (IRANK, "SPLIT")

CALL FCKIT_MPI_SETCOMMDEFAULT ("SPLIT")

YLGRID2 = GRID_FROM_NAMELIST ()

ISIZE = 10

CALL YLIOFS%INIT (KSIZE=ISIZE)

DO JLOC = 1, ISIZE
  YLIOFS%ILOC2 = JLOC
  YLIOFS%ILOC1 = 6
  YLDHIO = ATLAS_DH_t (YLGRID2)
  CALL ATLAS_PGD_IMPL (YLDHIO, YLIOFS, YLGRID2)
ENDDO

CALL YLTRAC%FINAL ()


CALL YLWORLD%FINAL ()
CALL YLSPLIT%FINAL ()

CALL ATLAS_LIBRARY%FINALISE()

WRITE (*, *) "--- STOP ---"

CONTAINS

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID_FROM_NAMELIST () RESULT (YLGRID)

REAL (KIND=JPRB) :: ZLON, ZLAT, ZEPS

ZLON = 46.2_JPRB
ZLAT =  2.0_JPRB
ZEPS =  0.1_JPRB

YLGRID = ATLAS_LONLATREGIONALGRID (4_JPIM, 4_JPIM, &
                                 & ZLON - ZEPS, ZLON + ZEPS, &
                                 & ZLAT + ZEPS, ZLAT - ZEPS)

CALL YLGRID%RETURN ()

END FUNCTION

END

