PROGRAM ATLAS_PGD

USE PARKIND1, ONLY : JPIM, JPRB
USE ATLAS_IO_FA, ONLY : ATLAS_IO_FA_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE ATLAS_MODULE  

!

IMPLICIT NONE

#include "atlas-prep-impl.h"

TYPE (ATLAS_IO_FA_t)              :: YLFAIO1
TYPE (ATLAS_IO_FA_t)              :: YLFAIO2

INTEGER (KIND=JPIM) :: NPROC, IRANK
TYPE (FCKIT_MPI_COMM) :: YLCOMM

CALL ATLAS_LIBRARY%INITIALISE ()

YLCOMM = FCKIT_MPI_COMM ()
NPROC  = YLCOMM%SIZE ()
IRANK  = YLCOMM%RANK ()

CALL LINUX_BIND (IRANK, NPROC)


CALL ATLAS_PREP_IMPL (YLFAIO1, YLFAIO2)

CALL ATLAS_LIBRARY%FINALISE()

WRITE (*, *) "--- STOP ---"

END
