PROGRAM ATLAS_PGD


USE PARKIND1, ONLY : JPIM, JPRB
USE ATLAS_IO_GATHSCAT, ONLY : ATLAS_IO_GATHSCAT_t
USE ATLAS_IO_DH, ONLY : ATLAS_IO_DH_t
USE ATLAS_FMT_NETCDF, ONLY : ATLAS_FMT_NETCDF_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE ATLAS_MODULE  
USE ATLAS_TRACE_MODULE

!

IMPLICIT NONE

#include "atlas-pgd-impl.h"

TYPE (ATLAS_IO_GATHSCAT_t)        :: YLIONC
TYPE (ATLAS_FMT_NETCDF_t), TARGET :: YLFMNC
TYPE (ATLAS_IO_DH_t)              :: YLDHIO
TYPE (ATLAS_STRUCTUREDGRID)       :: YLGRID2
TYPE (ATLAS_TRACE)                :: YLTRAC

INTEGER (KIND=JPIM) :: NPROC, IRANK
TYPE (FCKIT_MPI_COMM) :: YLCOMM

YLIONC = ATLAS_IO_GATHSCAT_t (YLFMNC, KPRC=1, KFLD=10)

CALL ATLAS_LIBRARY%INITIALISE ()

YLTRAC = ATLAS_TRACE (__FILE__, __LINE__, "ATLAS_PGD")

YLCOMM = FCKIT_MPI_COMM ()
NPROC  = YLCOMM%SIZE ()
IRANK  = YLCOMM%RANK ()

YLGRID2 = ATLAS_REGIONALGRID (NX=30, NY=40, NORTH=50._JPRB, WEST=-20._JPRB, SOUTH=10._JPRB, EAST=+10._JPRB)

YLDHIO = ATLAS_IO_DH_t (YLGRID2)

CALL ATLAS_PGD_IMPL (YLDHIO, YLIONC, YLGRID2)

CALL YLTRAC%FINAL ()

CALL ATLAS_LIBRARY%FINALISE()

WRITE (*, *) "--- STOP ---"

END

