PROGRAM ATLAS_PGD

USE PARKIND1, ONLY : JPIM, JPRB
USE ATLAS_IO_GATHSCAT, ONLY : ATLAS_IO_GATHSCAT_t
USE ATLAS_FMT_FA, ONLY : ATLAS_FMT_FA_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE ATLAS_MODULE  

!

IMPLICIT NONE

#include "atlas-prep-impl.h"

TYPE (ATLAS_IO_GATHSCAT_t)                   :: YLFAIO1
TYPE (ATLAS_FMT_FA_t), TARGET                :: YLFMFA1
TYPE (ATLAS_IO_GATHSCAT_t)                   :: YLFAIO2
TYPE (ATLAS_FMT_FA_t), TARGET                :: YLFMFA2

INTEGER (KIND=JPIM) :: NPROC, IRANK
TYPE (FCKIT_MPI_COMM) :: YLCOMM

CALL ATLAS_LIBRARY%INITIALISE ()

YLFAIO1 = ATLAS_IO_GATHSCAT_t (YLFMFA1)
YLFAIO2 = ATLAS_IO_GATHSCAT_t (YLFMFA2)

YLCOMM = FCKIT_MPI_COMM ()
NPROC  = YLCOMM%SIZE ()
IRANK  = YLCOMM%RANK ()

CALL LINUX_BIND (IRANK, NPROC)

CALL ATLAS_PREP_IMPL (YLFAIO1, YLFAIO2)

CALL ATLAS_LIBRARY%FINALISE()

WRITE (*, *) "--- STOP ---"

END

