PROGRAM ATLAS_ARPEGE_F

USE INTERPOLATION4_MOD
USE ATLAS_ARPEGE_MODULE
USE ATLAS_MODULE  

!

IMPLICIT NONE

TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRID1
TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRID2
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS) :: YLFSSC1
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS) :: YLFSSC2
TYPE (ATLAS_GRIDDISTRIBUTION)                :: YLDIST1
TYPE (ATLAS_GRIDDISTRIBUTION)                :: YLDIST2
TYPE (ATLAS_CONFIG)                          :: YLCONF1
TYPE (ATLAS_CONFIG)                          :: YLCONF2
TYPE (INTERPOLATION4)                        :: YLINTER

CALL ATLAS_LIBRARY%INITIALISE()

YLGRID1 = ATLAS_STRUCTUREDGRID ("L80x40")
YLGRID2 = ATLAS_STRUCTUREDGRID ("N16")

YLCONF1 = ATLAS_CONFIG(); CALL YLCONF1%SET ('type', 'checkerboard')
YLCONF2 = ATLAS_CONFIG(); CALL YLCONF2%SET ('type', 'equal_regions')

YLDIST1 = ATLAS_GRIDDISTRIBUTION (YLGRID1, YLCONF1)
YLDIST2 = ATLAS_GRIDDISTRIBUTION (YLGRID2, YLCONF2)

YLFSSC1 = ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS (YLGRID1, YLDIST1)
YLFSSC2 = ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS (YLGRID2, YLDIST2)

YLINTER = INTERPOLATION4 (YLDIST1, YLFSSC1, YLDIST2, YLFSSC2)

CALL ATLAS_LIBRARY%FINALISE()


END

