PROGRAM ATLAS_PGD


USE PARKIND1, ONLY : JPIM, JPRB
USE ATLAS_IO_GATHSCAT, ONLY : ATLAS_IO_GATHSCAT_t
USE ATLAS_IO_DH, ONLY : ATLAS_IO_DH_t
USE ATLAS_FMT_NETCDF, ONLY : ATLAS_FMT_NETCDF_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE ATLAS_MODULE  
USE ATLAS_HELPER
USE ATLAS_TRACE_MODULE
USE XRD_GETOPTIONS

!

IMPLICIT NONE

#include "atlas-pgd-impl.h"

TYPE (ATLAS_IO_GATHSCAT_t)        :: YLIONC
TYPE (ATLAS_FMT_NETCDF_t), TARGET :: YLFMNC
TYPE (ATLAS_IO_DH_t)              :: YLDHIO
TYPE (ATLAS_STRUCTUREDGRID)       :: YLGRID2
TYPE (ATLAS_TRACE)                :: YLTRAC

INTEGER (KIND=JPIM) :: NPROC, IRANK
TYPE (FCKIT_MPI_COMM) :: YLCOMM
LOGICAL :: LLNOROTATE, LLNOENVELOPPE
REAL (KIND=JPRB), POINTER :: ZELLIPSE (:) => NULL ()

CALL INITOPTIONS ()
CALL GETOPTION ('--noenveloppe', LLNOENVELOPPE)
CALL GETOPTION ('--norotate', LLNOROTATE)
CALL GETOPTION ('--ellipse', ZELLIPSE)
CALL CHECKOPTIONS ()


YLIONC = ATLAS_IO_GATHSCAT_t (YLFMNC, KPRC=1, KFLD=10)

CALL ATLAS_LIBRARY%INITIALISE ()

YLTRAC = ATLAS_TRACE (__FILE__, __LINE__, "ATLAS_PGD")

YLCOMM = FCKIT_MPI_COMM ()
NPROC  = YLCOMM%SIZE ()
IRANK  = YLCOMM%RANK ()

YLGRID2 = GRID_FROM_NAMELIST ()

YLDHIO = ATLAS_IO_DH_t (YLGRID2)

CALL ATLAS_PGD_IMPL (YLDHIO, YLIONC, YLGRID2,   &
                   & LDROTATE=.NOT. LLNOROTATE, &
                   & PELLIPSE=ZELLIPSE,         &
                   & LDENVELOPPE=.NOT. LLNOENVELOPPE)

CALL YLTRAC%FINAL ()

CALL ATLAS_LIBRARY%FINALISE()

WRITE (*, *) "--- STOP ---"

END

