INTERFACE
FUNCTION ATLAS_COMPUTE_COVERS (YDFSSC1, YDFSSC2, YDCOVR1, YDINTEA, LDOPENMP) RESULT (YLFLDS2)

USE PARKIND1, ONLY : JPIM, JPRB
USE INTERPOLATIONA_MOD
USE ATLAS_MODULE  

IMPLICIT NONE

TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDFSSC1
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDFSSC2
TYPE (ATLAS_FIELD),                           INTENT (IN) :: YDCOVR1
TYPE (INTERPOLATIONA),                        INTENT (IN) :: YDINTEA
LOGICAL,                                      INTENT (IN) :: LDOPENMP

TYPE (ATLAS_FIELDSET) :: YLFLDS2
END FUNCTION
END INTERFACE
