INTERFACE
SUBROUTINE ATLAS_PGD_IMPL (YDIO1, YDIO2, YDGRID2, LDOPENMP, LDROTATE, PELLIPSE)
USE PARKIND1, ONLY : JPRB, JPIM
USE ATLAS_IO, ONLY : ATLAS_IO_t
USE ATLAS_MODULE  
IMPLICIT NONE
CLASS (ATLAS_IO_t)                           :: YDIO1
CLASS (ATLAS_IO_t)                           :: YDIO2
CLASS (ATLAS_STRUCTUREDGRID)                 :: YDGRID2
LOGICAL, OPTIONAL                            :: LDOPENMP
LOGICAL, OPTIONAL                            :: LDROTATE
REAL (KIND=JPRB), OPTIONAL, POINTER          :: PELLIPSE (:)
END SUBROUTINE
END INTERFACE

