INTERFACE
SUBROUTINE ATLAS_PREP_IMPL (YDIO1, YDIO2)
USE ATLAS_IO, ONLY : ATLAS_IO_t
USE ATLAS_MODULE  
IMPLICIT NONE
CLASS (ATLAS_IO_t)                           :: YDIO1
CLASS (ATLAS_IO_t)                           :: YDIO2
END SUBROUTINE
END INTERFACE
