INTERFACE
FUNCTION ATLAS_COMPUTE_SSO2 (YDFSSC1, YDFSSC2, YDOROG1, YDINTEA, LDOPENMP, LDROTATE) RESULT (YLFLDS2)

USE PARKIND1, ONLY : JPIM, JPRB
USE INTERPOLATIONA_MOD
USE ATLAS_MODULE  

IMPLICIT NONE

TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDFSSC1
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDFSSC2
TYPE (ATLAS_FIELD),                           INTENT (IN) :: YDOROG1
TYPE (INTERPOLATIONA),                        INTENT (IN) :: YDINTEA
LOGICAL,                                      INTENT (IN) :: LDOPENMP
LOGICAL,                                      INTENT (IN) :: LDROTATE

TYPE (ATLAS_FIELDSET) :: YLFLDS2

END FUNCTION
END INTERFACE
