SUBROUTINE ATLAS_PREP_IMPL (YDIO1, YDIO2)

USE PARKIND1, ONLY : JPIM, JPRB
USE INTERPOLATIONA_MOD
USE INTERPOLATION4_MOD
USE ATLAS_IO, ONLY : ATLAS_IO_t
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM
USE ATLAS_MODULE  
USE ATLAS_HELPER

#include "atlas-abort.h"

!

IMPLICIT NONE

CLASS (ATLAS_IO_t)                           :: YDIO1
CLASS (ATLAS_IO_t)                           :: YDIO2

TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRIDPRE1
TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRIDPGD1
TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRID1
TYPE (ATLAS_STRUCTUREDGRID)                  :: YLGRID2

TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS) :: YLFSSC1
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS) :: YLFSSC2
TYPE (ATLAS_GRIDDISTRIBUTION)                :: YLDIST1
TYPE (ATLAS_GRIDDISTRIBUTION)                :: YLDIST2
TYPE (INTERPOLATIONA)                        :: YLINTEA
TYPE (INTERPOLATION4)                        :: YLINTE4
TYPE (ATLAS_FIELDSET)                        :: YLFLDS1  
TYPE (ATLAS_FIELDSET)                        :: YLFLDS2
TYPE (FCKIT_MPI_COMM)                        :: YLCOMM

INTEGER (KIND=JPIM) :: I, JFLD
INTEGER (KIND=JPIM) :: NPROC, IRANK

TYPE (ATLAS_FIELD), ALLOCATABLE :: YLFL1 (:), YLFL2 (:)
TYPE (PTR),         ALLOCATABLE :: YLPT1 (:), YLPT2 (:)

CHARACTER (LEN=16), DIMENSION (31) :: CLNAME = &
[ 'SFX.SST         ', 'SFX.Z0SEA       ', 'SFX.SSS         ', 'SFX.TS_WATER    ', &
& 'SFX.Z0WATER     ', 'X001TG1         ', 'X001TG2         ', 'X001WG1         ', &
& 'X001WG2         ', 'X001WG3         ', 'X001WGI1        ', 'X001WGI2        ', &
& 'X001WR          ', 'X001ICE_STO     ', 'X001WSN_VEG1    ', 'X001RSN_VEG1    ', &
& 'X001ASN_VEG     ', 'SFX.TSRAD_NAT   ', 'X001RESA        ', 'X001LAI         ', &
& 'X001VEG         ', 'X001DG2         ', 'X001RSMIN       ', 'X001ALBNIR_S    ', &
& 'X001ALBVIS_S    ', 'X001ALBUV_S     ', 'X001ALBNIR_ISBA ', 'X001ALBVIS_ISBA ', &
& 'X001ALBUV_ISBA  ', 'SFX.T2M         ', 'SFX.HU2M        ']

REAL (KIND=JPRB), PARAMETER :: ZUNDEF = HUGE (1._JPRB)

LOGICAL, PARAMETER :: LGARDEN = .FALSE., LWATER_TO_NATURE = .FALSE., LTOWN_TO_ROCK = .TRUE.

YLCOMM = FCKIT_MPI_COMM ()
NPROC  = YLCOMM%SIZE ()
IRANK  = YLCOMM%RANK ()

YLGRIDPRE1 = YDIO1%GRID ('PRE1')
YLGRIDPGD1 = YDIO1%GRID ('PGD1')



IF (.NOT. GRID_EQ (YLGRIDPRE1, YLGRIDPGD1)) THEN
  CALL ABORT ('GEOMETRY MISMATCH')
ENDIF

YLGRID1 = YLGRIDPRE1

CALL YLGRIDPRE1%FINAL ()
CALL YLGRIDPGD1%FINAL ()

YLGRID2 = YDIO2%GRID ('PGD2')

CALL CREATE_DIST (YLGRID1, YLDIST1)
CALL CREATE_DIST (YLGRID2, YLDIST2)

YLFSSC1 = ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS (YLGRID1, YLDIST1)
YLFSSC2 = ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS (YLGRID2, YLDIST2)

YLFLDS1 = YDIO1%READ ('PRE1', CLNAME, YLFSSC1, ZUNDEF)

YLINTEA = INTERPOLATIONA (YLDIST1, YLFSSC1, YLDIST2, YLFSSC2)
YLINTE4 = INTERPOLATION4 (YLDIST1, YLFSSC1, YLDIST2, YLFSSC2)

#ifdef UNDEF

BLOCK
  TYPE (ATLAS_FIELDSET) :: YLFLDS24
  TYPE (ATLAS_FIELD) :: YLFLDA, YLFLD4
  REAL (KIND=JPRB), POINTER :: ZDATA (:), ZDAT4 (:)
  YLFLDS2  = YLINTEA%INTERPOLATE (YLFLDS1)
  YLFLDS24 = YLINTE4%INTERPOLATE (YLFLDS1)

  DO JFLD = 1, YLFLDS2%SIZE ()

    YLFLDA = YLFLDS2 %FIELD (JFLD)
    YLFLD4 = YLFLDS24%FIELD (JFLD)

    IF (YLFLDA%NAME () /= YLFLD4%NAME ()) &
      & CALL ABORT ('FIELD MISMATCH')

    CALL YLFLDA%DATA (ZDATA)
    CALL YLFLD4%DATA (ZDAT4)
   
!$OMP WORKSHARE
    WHERE (ZDATA == ZUNDEF)
      ZDATA = ZDAT4
    ENDWHERE
!$OMP END WORKSHARE

    CALL YLFLDA%FINAL ()
    CALL YLFLD4%FINAL ()

  ENDDO

  CALL YLFLDS24%FINAL ()

ENDBLOCK

CALL YDIO2%WRITE ('PRE2', YLFLDS2, YLFSSC2)
#endif

CALL YLINTE4%FINAL ()
CALL YLINTEA%FINAL ()
CALL YLGRID1%FINAL ()
CALL YLGRID2%FINAL ()
CALL YLDIST1%FINAL ()
CALL YLDIST2%FINAL ()
CALL YLFLDS1%FINAL ()
CALL YLFLDS2%FINAL ()
CALL YLFSSC1%FINAL ()
CALL YLFSSC2%FINAL ()

END

