PROGRAM ESSAI

USE MPL_MODULE, ONLY : MPL_MYRANK, MPL_NUMPROC
USE MPL_INIT_MOD, ONLY : MPL_INIT
USE MPL_END_MOD, ONLY : MPL_END

USE PARKIND1, ONLY : JPRB, JPIM
USE MYM1QN3MOD, ONLY : MYM1QN3CTX, M1QN3

IMPLICIT NONE

CHARACTER (LEN=3) NORMTYPE

INTEGER (KIND=JPIM) I,N,IMP,IO,IMODE(3),OMODE,NITER,NSIM,IZ(5),NDZ, INDIC,REVERSE
INTEGER (KIND=JPIM) N1, N2
REAL (KIND=JPRB) C,F,DX,DF1,EPSREL
REAL (KIND=JPRB), ALLOCATABLE :: DZ(:)
REAL (KIND=JPRB), ALLOCATABLE :: X(:),G(:)

INTEGER (KIND=JPIM), PARAMETER :: JDIMMAX = 100
REAL (KIND=JPRB),    TARGET :: COEF (JDIMMAX) 
INTEGER (KIND=JPIM), TARGET :: EXPO (JDIMMAX)
INTEGER (KIND=JPIM) :: JDIM 
TYPE (MYM1QN3CTX) :: YLCTX

NAMELIST / NAMDIM / JDIM, COEF, EXPO

READ (4, NML=NAMDIM)

WRITE (*, '(" COEF = ",100E12.4)') COEF (1:JDIM)
WRITE (*, '(" EXPO = ",100I12)')   EXPO (1:JDIM)

CALL MPL_INIT (LDENV = .FALSE.)

YLCTX%NPROC = MPL_NUMPROC
YLCTX%MYPROC = MPL_MYRANK ()

!
! --- INITIALIZATION
!
N=JDIM

N1 = 1 + (N * (YLCTX%MYPROC-1)) / YLCTX%NPROC
N2 = 0 + (N * (YLCTX%MYPROC+0)) / YLCTX%NPROC

ALLOCATE (YLCTX%N (YLCTX%NPROC))
BLOCK
  INTEGER (KIND=JPIM) I1, I2, IPROC
  DO IPROC = 1, YLCTX%NPROC
    I1 = 1 + (N * (IPROC-1)) / YLCTX%NPROC
    I2 = 0 + (N * (IPROC+0)) / YLCTX%NPROC
    YLCTX%N (IPROC) = I2-I1+1
  ENDDO
ENDBLOCK


ALLOCATE (X (N2-N1+1), G (N2-N1+1))

BLOCK
INTEGER (KIND=JPIM) I1, I2
I1 = 1 + (20000 * (YLCTX%MYPROC-1)) / YLCTX%NPROC
I2 = 0 + (20000 * (YLCTX%MYPROC+0)) / YLCTX%NPROC
NDZ=I2-I1+1
ENDBLOCK
ALLOCATE (DZ (NDZ))

YLCTX%COEF => COEF (N1:N2)
YLCTX%EXPO => EXPO (N1:N2)

DO I=1,N2-N1+1
    X(I)=5.D+0
ENDDO
!
! --- FIRST CALL THE SIMULATOR
!
INDIC=4
CALL YLCTX%SIMUL (INDIC,N2-N1+1,X,F,G)
!
! --- CALL THE OPTIMIZATION CODE
!     NORMTYPE CAN BE 'SUP' FOR SUP-NORM, 'TWO' FOR 2-NORM, 'DFN' FOR THE NORM DEFINED BY PROSCA
!
DX=1.E-10
DF1=F
EPSREL=1.E-5
NITER=200
NSIM=200
NORMTYPE = 'DFN'
IO=6
IMP=5
IMODE(1)=0
IMODE(2)=0
IMODE(3)=0
REVERSE=0
CALL YLCTX%M1QN3 (N2-N1+1,X,F,G,DX,DF1,EPSREL,      &
& NORMTYPE,IMP,IO,IMODE,OMODE,NITER,NSIM,IZ,DZ,NDZ, &
& REVERSE,INDIC)


CALL YLCTX%P2 (X, N2-N1+1)

CALL MPL_END

END

