MODULE ATLAS_FMT

USE ATLAS_MODULE

IMPLICIT NONE

TYPE, ABSTRACT :: ATLAS_FMT_t
CONTAINS

  PROCEDURE (GRID_f),     DEFERRED, PASS (THIS) :: GRID
  PROCEDURE (READ_f),     DEFERRED, PASS (THIS) :: READ    
  PROCEDURE (WRITE_f),    DEFERRED, PASS (THIS) :: WRITE   
  PROCEDURE (OPEN_f),     DEFERRED, PASS (THIS) :: OPEN    
  PROCEDURE (CLOSE_f),    DEFERRED, PASS (THIS) :: CLOSE   

END TYPE ATLAS_FMT_t

PRIVATE

PUBLIC :: ATLAS_FMT_t


ABSTRACT INTERFACE

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID_f (THIS, CDFILE)
USE ATLAS_MODULE
IMPORT :: ATLAS_FMT_t
CLASS (ATLAS_FMT_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),   INTENT (IN) :: CDFILE
END FUNCTION GRID_f

SUBROUTINE READ_f (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
USE PARKIND1, ONLY : JPRB
IMPORT :: ATLAS_FMT_t
CLASS (ATLAS_FMT_t),           INTENT (IN)    :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),              INTENT (OUT)   :: PFLDG (:)
LOGICAL,                       INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),              INTENT (INOUT) :: PUNDEF
END SUBROUTINE READ_f

SUBROUTINE WRITE_f (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
USE PARKIND1, ONLY : JPRB
IMPORT :: ATLAS_FMT_t
CLASS (ATLAS_FMT_t),           INTENT (IN)    :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),              INTENT (IN)    :: PFLDG (:)
LOGICAL,                       INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),              INTENT (INOUT) :: PUNDEF
END SUBROUTINE WRITE_f

SUBROUTINE OPEN_f (THIS, CDFILE, YDGRID)
USE ATLAS_MODULE
IMPORT :: ATLAS_FMT_t
CLASS (ATLAS_FMT_t),           INTENT (INOUT) :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDFILE
CLASS (ATLAS_STRUCTUREDGRID),  INTENT (IN)    :: YDGRID
END SUBROUTINE OPEN_f

SUBROUTINE CLOSE_f (THIS)
IMPORT :: ATLAS_FMT_t
CLASS (ATLAS_FMT_t),           INTENT (INOUT) :: THIS
END SUBROUTINE CLOSE_f

END INTERFACE

END MODULE 

