MODULE ATLAS_IO_NULL

USE ATLAS_IO, ONLY : ATLAS_IO_t

USE PARKIND1, ONLY : JPRB, JPIM
USE ATLAS_MODULE

#include "atlas-abort.h"

IMPLICIT NONE

TYPE, EXTENDS (ATLAS_IO_t) :: ATLAS_IO_NULL_t
CONTAINS

  PROCEDURE :: GRID
  PROCEDURE :: READ    
  PROCEDURE :: WRITE   

END TYPE

PRIVATE
PUBLIC :: ATLAS_IO_NULL_t

CONTAINS

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID (THIS, CDFILE) RESULT (YLGRID)

CLASS (ATLAS_IO_NULL_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),       INTENT (IN) :: CDFILE

CALL ATLAS_ABORT ('NOT IMPLEMENTED')

END FUNCTION

TYPE (ATLAS_FIELDSET) FUNCTION READ (THIS, CDFILE, CDNAME, YDSTCO, PUNDEF, PSCALE) RESULT (YLFLST)

CLASS (ATLAS_IO_NULL_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),       INTENT (IN) :: CDFILE
CHARACTER (LEN=*),       INTENT (IN) :: CDNAME (:)
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO
REAL (KIND=JPRB),        INTENT (IN), OPTIONAL :: PUNDEF, PSCALE

CALL ATLAS_ABORT ('NOT IMPLEMENTED')

END FUNCTION

SUBROUTINE WRITE (THIS, CDFILE, YDFLST, YDSTCO)

CLASS (ATLAS_IO_NULL_t),    INTENT (IN) :: THIS
CHARACTER (LEN=*),          INTENT (IN) :: CDFILE
TYPE (ATLAS_FIELDSET),      INTENT (IN) :: YDFLST
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO

INTEGER (KIND=JPIM) :: INFLD, JFLD, ISIZEG
TYPE (ATLAS_FIELD)          :: YLFLDL 
TYPE (ATLAS_STRUCTUREDGRID) :: YLGRID

INFLD  = YDFLST%SIZE ()
YLGRID = YDSTCO%GRID ()

DO JFLD = 1, INFLD
BLOCK
  CHARACTER (LEN=16)  :: CLNOMA

  YLFLDL = YDFLST%FIELD (JFLD)

  CLNOMA = YLFLDL%NAME ()
  ISIZEG = INT (YLGRID%SIZE (), JPIM)

  PRINT *, CLNOMA, " ", ISIZEG

  CALL YLFLDL%FINAL ()

ENDBLOCK
ENDDO

CALL YLGRID%FINAL ()

END SUBROUTINE

END MODULE

