MODULE ATLAS_IO

USE ATLAS_MODULE

IMPLICIT NONE

TYPE, ABSTRACT :: ATLAS_IO_t
CONTAINS

  PROCEDURE (GRID_f),     DEFERRED, PASS (THIS) :: GRID
  PROCEDURE (READ_f),     DEFERRED, PASS (THIS) :: READ    
  PROCEDURE (WRITE_f),    DEFERRED, PASS (THIS) :: WRITE   

END TYPE ATLAS_IO_t

PRIVATE

PUBLIC :: ATLAS_IO_t


ABSTRACT INTERFACE

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID_f (THIS, CDFILE)
USE ATLAS_MODULE
IMPORT :: ATLAS_IO_t
CLASS (ATLAS_IO_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),  INTENT (IN) :: CDFILE
END FUNCTION

TYPE (ATLAS_FIELDSET) FUNCTION READ_f (THIS, CDFILE, CDNAME, YDSTCO, PUNDEF, PSCALE)
USE ATLAS_MODULE
USE PARKIND1, ONLY : JPRB
IMPORT :: ATLAS_IO_t
CLASS (ATLAS_IO_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),  INTENT (IN) :: CDFILE
CHARACTER (LEN=*),  INTENT (IN) :: CDNAME (:)
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO
REAL (KIND=JPRB),   INTENT (IN), OPTIONAL :: PUNDEF, PSCALE
END FUNCTION

SUBROUTINE WRITE_f (THIS, CDFILE, YDFLST, YDSTCO)
USE ATLAS_MODULE
IMPORT :: ATLAS_IO_t
CLASS (ATLAS_IO_t),    INTENT (IN) :: THIS
CHARACTER (LEN=*),     INTENT (IN) :: CDFILE
TYPE (ATLAS_FIELDSET), INTENT (IN) :: YDFLST
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO
END SUBROUTINE

END INTERFACE

END MODULE 
