MODULE ATLAS_FMT_FORTRAN_BINARY

USE ATLAS_FMT, ONLY : ATLAS_FMT_t

USE PARKIND1, ONLY : JPRB, JPIM
USE ATLAS_MODULE

#include "atlas-abort.h"

IMPLICIT NONE

TYPE, EXTENDS (ATLAS_FMT_t) :: ATLAS_FMT_FORTRAN_BINARY_t

CONTAINS

  PROCEDURE :: OPEN
  PROCEDURE :: CLOSE
  PROCEDURE :: GRID
  PROCEDURE :: READ    
  PROCEDURE :: WRITE   

END TYPE

PRIVATE

PUBLIC :: ATLAS_FMT_FORTRAN_BINARY_t

CONTAINS

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID (THIS, CDFILE) RESULT (YLGRID)
CLASS (ATLAS_FMT_FORTRAN_BINARY_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),                  INTENT (IN) :: CDFILE

CALL YLGRID%RETURN ()

END FUNCTION

SUBROUTINE OPEN (THIS, CDFILE, YDGRID)
CLASS (ATLAS_FMT_FORTRAN_BINARY_t),   INTENT (INOUT) :: THIS
CHARACTER (LEN=*),                    INTENT (IN)    :: CDFILE
CLASS (ATLAS_STRUCTUREDGRID),         INTENT (IN)    :: YDGRID
END SUBROUTINE OPEN

SUBROUTINE CLOSE (THIS)
CLASS (ATLAS_FMT_FORTRAN_BINARY_t),  INTENT (INOUT) :: THIS
END SUBROUTINE


SUBROUTINE READ (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
CLASS (ATLAS_FMT_FORTRAN_BINARY_t),  INTENT (IN)    :: THIS
CHARACTER (LEN=*),                   INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),                    INTENT (OUT)   :: PFLDG (:)
LOGICAL,                             INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),                    INTENT (INOUT) :: PUNDEF

END SUBROUTINE

SUBROUTINE WRITE (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
CLASS (ATLAS_FMT_FORTRAN_BINARY_t), INTENT (IN)    :: THIS
CHARACTER (LEN=*),                  INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),                   INTENT (OUT)   :: PFLDG (:)
LOGICAL,                            INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),                   INTENT (INOUT) :: PUNDEF

END SUBROUTINE

END MODULE

