MODULE ATLAS_IO_FIELDSET

USE ATLAS_IO, ONLY : ATLAS_IO_t

USE PARKIND1, ONLY : JPRB, JPIM
USE ATLAS_MODULE

#include "atlas-abort.h"

IMPLICIT NONE

TYPE, EXTENDS (ATLAS_IO_t) :: ATLAS_IO_FIELDSET_t
  TYPE (ATLAS_FIELDSET) :: YFLDSET
  INTEGER (KIND=JPIM) :: ISIZE = -1
  INTEGER (KIND=JPIM) :: ILOC1 = -1, ILOC2 = -1
CONTAINS

  PROCEDURE :: GRID
  PROCEDURE :: READ    
  PROCEDURE :: WRITE   
  PROCEDURE, PASS (THIS) :: INIT

END TYPE

PRIVATE
PUBLIC :: ATLAS_IO_FIELDSET_t

CONTAINS

SUBROUTINE INIT (THIS, KSIZE)

CLASS (ATLAS_IO_FIELDSET_t), INTENT (INOUT) :: THIS
INTEGER (KIND=JPIM),         INTENT (IN)    :: KSIZE

THIS%ISIZE = KSIZE
THIS%YFLDSET = ATLAS_FIELDSET ()

END SUBROUTINE

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID (THIS, CDFILE) RESULT (YLGRID)

CLASS (ATLAS_IO_FIELDSET_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),           INTENT (IN) :: CDFILE

CALL ABORT ('NOT IMPLEMENTED')

END FUNCTION

TYPE (ATLAS_FIELDSET) FUNCTION READ (THIS, CDFILE, CDNAME, YDSTCO, PUNDEF, PSCALE) RESULT (YLFLST)

CLASS (ATLAS_IO_FIELDSET_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),           INTENT (IN) :: CDFILE
CHARACTER (LEN=*),           INTENT (IN) :: CDNAME (:)
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO
REAL (KIND=JPRB),            INTENT (IN), OPTIONAL :: PUNDEF, PSCALE

CALL ABORT ('NOT IMPLEMENTED')

END FUNCTION

SUBROUTINE WRITE (THIS, CDFILE, YDFLST, YDSTCO)

CLASS (ATLAS_IO_FIELDSET_t),    INTENT (IN) :: THIS
CHARACTER (LEN=*),              INTENT (IN) :: CDFILE
TYPE (ATLAS_FIELDSET),          INTENT (IN) :: YDFLST
TYPE (ATLAS_FUNCTIONSPACE_STRUCTUREDCOLUMNS), INTENT (IN) :: YDSTCO

INTEGER (KIND=JPIM)         :: INFLD, JFLD
TYPE (ATLAS_FIELD)          :: YLFLDL1, YLFLDL2

INFLD  = YDFLST%SIZE ()

DO JFLD = 1, INFLD
BLOCK
  CHARACTER (LEN=16)  :: CLNAME
  REAL (KIND=JPRB), POINTER :: ZDATA1 (:), ZDATA2 (:)

  YLFLDL1 = YDFLST%FIELD (JFLD)

  CLNAME = YLFLDL1%NAME ()

  IF (THIS%YFLDSET%HAS_FIELD (CLNAME)) THEN
    YLFLDL2 = THIS%YFLDSET%FIELD (CLNAME)
  ELSE
    YLFLDL2 = ATLAS_FIELD (NAME=TRIM (CLNAME), KIND=JPRB, SHAPE=[THIS%ISIZE])
    CALL THIS%YFLDSET%ADD (YLFLDL2)
  ENDIF

  CALL YLFLDL1%DATA (ZDATA1)
  CALL YLFLDL2%DATA (ZDATA2)

  ZDATA2 (THIS%ILOC2) = ZDATA1 (THIS%ILOC1)

  CALL YLFLDL1%FINAL ()
  CALL YLFLDL2%FINAL ()

ENDBLOCK
ENDDO

END SUBROUTINE

END MODULE

