MODULE ATLAS_IO_FA

USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM

USE ATLAS_IO_GATHSCAT, ONLY : ATLAS_IO_GATHSCAT_t
USE ATLAS_FMT_FA, ONLY : ATLAS_FMT_FA_t

USE PARKIND1, ONLY : JPRB, JPIM
USE ATLAS_MODULE

#include "atlas-abort.h"

IMPLICIT NONE

TYPE, EXTENDS (ATLAS_IO_GATHSCAT_t) :: ATLAS_IO_FA_t

  TYPE (ATLAS_FMT_FA_t) :: YLFMT

CONTAINS

  PROCEDURE :: FORMAT

END TYPE

PRIVATE
PUBLIC :: ATLAS_IO_FA_t

CONTAINS

FUNCTION FORMAT (THIS) RESULT (YLFMT)
USE ATLAS_FMT, ONLY : ATLAS_FMT_t
IMPLICIT NONE
CLASS (ATLAS_IO_FA_t), INTENT (IN), TARGET :: THIS
CLASS (ATLAS_FMT_t), POINTER :: YLFMT
YLFMT => THIS%YLFMT
END FUNCTION FORMAT

END MODULE

