MODULE ATLAS_FMT_NETCDF

USE ATLAS_MODULE
USE ATLAS_FMT
USE FCKIT_MODULE, ONLY : FCKIT_MPI_COMM

#include "atlas-abort.h"

IMPLICIT NONE

TYPE, EXTENDS (ATLAS_FMT_t) :: ATLAS_FMT_NETCDF_t
CONTAINS

  PROCEDURE :: GRID
  PROCEDURE :: READ    
  PROCEDURE :: WRITE   
  PROCEDURE :: OPEN    
  PROCEDURE :: CLOSE   

END TYPE ATLAS_FMT_NETCDF_t

PRIVATE

PUBLIC :: ATLAS_FMT_NETCDF_t

CONTAINS

TYPE (ATLAS_STRUCTUREDGRID) FUNCTION GRID (THIS, CDFILE)
USE ATLAS_MODULE
CLASS (ATLAS_FMT_NETCDF_t), INTENT (IN) :: THIS
CHARACTER (LEN=*),          INTENT (IN) :: CDFILE

END FUNCTION GRID

SUBROUTINE READ (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
USE PARKIND1, ONLY : JPRB
CLASS (ATLAS_FMT_NETCDF_t),    INTENT (IN)    :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),              INTENT (OUT)   :: PFLDG (:)
LOGICAL,                       INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),              INTENT (INOUT) :: PUNDEF
END SUBROUTINE READ

SUBROUTINE WRITE (THIS, CDNAME, PFLDG, LDUNDEF, PUNDEF)
USE PARKIND1, ONLY : JPRB
CLASS (ATLAS_FMT_NETCDF_t),    INTENT (IN)    :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDNAME
REAL (KIND=JPRB),              INTENT (IN)    :: PFLDG (:)
LOGICAL,                       INTENT (INOUT) :: LDUNDEF
REAL (KIND=JPRB),              INTENT (INOUT) :: PUNDEF

TYPE (FCKIT_MPI_COMM) :: YLCOMM

YLCOMM = FCKIT_MPI_COMM ()

! Write field

WRITE (*, '(" WRITE ",A16,", MYPROC = ",I4,L3,E12.4,I8)') CDNAME, YLCOMM%RANK () + 1, LDUNDEF, PUNDEF, SIZE (PFLDG)

CALL YLCOMM%FINAL ()

END SUBROUTINE WRITE

SUBROUTINE OPEN (THIS, CDFILE, YDGRID)
USE ATLAS_MODULE
CLASS (ATLAS_FMT_NETCDF_t),    INTENT (INOUT) :: THIS
CHARACTER (LEN=*),             INTENT (IN)    :: CDFILE
CLASS (ATLAS_STRUCTUREDGRID),  INTENT (IN)    :: YDGRID

LOGICAL :: LLEXIST

TYPE (FCKIT_MPI_COMM) :: YLCOMM

YLCOMM = FCKIT_MPI_COMM ()

INQUIRE (FILE=TRIM (CDFILE), EXIST=LLEXIST)

WRITE (*, '(" OPEN  ",A16,", MYPROC = ",I4)') TRIM (CDFILE), YLCOMM%RANK () + 1

IF (LLEXIST) THEN
  ! Open file and check the geometry is the same as YDGRID
ELSE
  ! Create file with geometry YDGRID
ENDIF

CALL YLCOMM%FINAL ()

END SUBROUTINE OPEN

SUBROUTINE CLOSE (THIS)
CLASS (ATLAS_FMT_NETCDF_t),    INTENT (INOUT) :: THIS

TYPE (FCKIT_MPI_COMM) :: YLCOMM

YLCOMM = FCKIT_MPI_COMM ()

WRITE (*, '(" CLOSE ",A16,", MYPROC = ",I4)') " ", YLCOMM%RANK () + 1

CALL YLCOMM%FINAL ()

END SUBROUTINE CLOSE

END MODULE 

